version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
      - echo Installing source NPM dependencies...
      - apt-get update -y
      - apt-get install -y apt-transport-https
      - npm install forever -g
      - npm install -g @angular/cli
      - npm install
      - node node_modules/node-sass/scripts/install.js
      - npm rebuild node-sass
  build:
    commands:
      - echo Build started on `date`
      - ./env.sh
      # - while IFS='=' read -r name value ; do  if [[ $name == 'FILESTACK_'* ]]; then sed -i "s#<$name>#${!name}#g" src/environments/filestack.ts; fi; done < <(env)
      - ng build --configuration=custom
      - npm run generate-version
  post_build:
    commands:
      - aws s3 sync www/ s3://$S3_BUCKET/ --delete
      - aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths '/*'
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - template.yml
    - README.md
    - package.json
    - package-lock.json
    - tsconfig.json
    - tslint.json
    - angular.json
    - ionic.config.json
    - appspec.yml
    - scripts/*
    - src/**/*
    - www/**/*
    - node_modules/**/*
