version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  pre_build:
    commands:
      - echo "Nothing to pre_build"
  build:
    commands:
      - ng build
      - ng test --karmaConfig=src/karma.conf.aws.js --no-watch
  post_build:
    commands:
      - now=$(date -u +'%S-%M-%H-%d-%m-%Y') && aws s3 sync coverage/ s3://sydney-test-data/ui-automation/reports/appv2_coverage/coverage_$now
      - printenv