version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
      docker: 18
    commands:
      # - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
      # - sudo apt-get install -y nodejs
      - echo Installing source NPM dependencies...
      - apt-get update -y
      - apt-get install -y apt-transport-https
      # - apt-get install -y s3cmd
      - npm install forever -g
      - npm install -g @angular/cli
      - npm install
      - node node_modules/node-sass/scripts/install.js
      - npm rebuild node-sass
  build:
    commands:
      - echo Build started on `date`
      - ng build --configuration=$BUILD_CONFIG
  post_build:
    commands:
      # - s3cmd sync www/ s3://$S3_BUCKET/ --delete-removed --recursive --cf-invalidate --add-header=Cache-Control:max-age=0,public
      - aws s3 sync www/ s3://$S3_BUCKET/ --delete
      - aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths '/*'
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - template.yml
    - README.md
    - package.json
    - package-lock.json
    - tsconfig.json
    - tslint.json
    - angular.json
    - ionic.config.json
    - appspec.yml
    - scripts/*
    - src/**/*
    - www/**/*
    - node_modules/**/*