version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Install started on `date`
      - npm install forever -g
      - npm install -g @angular/cli
      - npm install
      - echo Install completed on `date`
  build:
    commands:
      - echo Build started on `date`
      - export lintresult=$(ng lint --format=verbose)
  post_build:
    commands:
      - aws sns publish --topic-arn $NOTIFIER_TOPIC --message "$lintresult"
      - echo Build completed on `date`
