version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Install started on `date`
      - npm install forever -g
      - npm install -g @angular/cli
      - npm install
      - echo Install completed on `date`
  build:
    commands:
      - echo Build started on `date`
      - aws sns publish --topic-arn $NOTIFIER_TOPIC --message "practera-app-v2-dev-lint starts for $CODEBUILD_SOURCE_VERSION"
      - lintresult=$(ng lint --format=verbose)
  post_build:
    commands:
      - aws sns publish --topic-arn $NOTIFIER_TOPIC --message "$CODEBUILD_SOURCE_VERSION lint result is $lintresult"
      - echo Build completed on `date`
