version: 0.2

phases:
  install:
    commands:
      - echo Install started on `date`
      - sudo npm install forever -g
      - sudo npm install -g @angular/cli
      - sudo npm install
      - echo Install completed on `date`
  build:
    commands:
      - echo Build started on `date`
      - sudo ng lint
  post_build:
    commands:
      - echo Build completed on `date`
