version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  pre_build:
    commands:
      - echo "Nothing to pre_build"
  build:
    commands:
      - ng build
      - ng test --karmaConfig=src/karma.conf.aws.js --no-watch
  post_build:
    commands:
      - printenv