version: 0.2

phases:
  install:
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
      - curl -sL https://rpm.nodesource.com/setup_10.x | bash -
      - yum install -y nodejs
      - npm install forever -g
      - npm install -g @angular/cli
      - npm install
      - node node_modules/node-sass/scripts/install.js
      - npm rebuild node-sass
  build:
    commands:
      - ng build --configuration=stage
artifacts:
  type: zip
  files:
    - template.yml
    - README.md
    - package.json
    - package-lock.json
    - tsconfig.json
    - tslint.json
    - angular.json
    - ionic.config.json
    - appspec.yml
    - scripts/*
    - src/**/*
    - www/**/*
    - node_modules/**/*