version: 0.2
phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - echo "Nothing to pre_build"
  build:
    commands:
      - ng build --configuration=$BUILD_CONFIG
      - ng test --karmaConfig=src/karma.conf.aws.js --no-watch
  post_build:
    commands:
      - export now=$(date -u +'%S-%M-%H-%d-%m-%Y') && \
        aws s3 sync coverage/ $REPORT_PATH/coverage_$now && \
        aws sns publish --topic-arn $NOTIFIER_TOPIC --message "practea-app-v2 tests completed for "$CODEBUILD_SOURCE_VERSION", the report is "$REPORT_URL"/coverage_$now/index.html"
      - printenv