version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
      - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - echo Installing source NPM dependencies...
      - sudo apt-get update -y
      - sudo apt-get install -y apt-transport-https
      - sudo npm install forever -g
      - sudo npm install -g @angular/cli
      - sudo npm install
      - sudo node node_modules/node-sass/scripts/install.js
      - sudo npm rebuild node-sass
  build:
    commands:
      - echo Build started on `date`
      - while IFS='=' read -r name value ; do  if [[ $name == 'CUSTOM_'* ]]; then sed -i "s#<$name>#${!name}#g" src/environments/environment.custom.ts; fi; done < <(env)
      - while IFS='=' read -r name value ; do  if [[ $name == 'FILESTACK_'* ]]; then sed -i "s#<$name>#${!name}#g" src/environments/filestack.ts; fi; done < <(env)
      - sudo ng build --configuration=custom
      - cat src/environment/environment.ts
      - cat src/environment/filestack.ts
      - sudo npm run generate-version
  post_build:
    commands:
      - aws s3 sync www/ s3://$S3_BUCKET/ --delete
      - aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths '/*'
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - template.yml
    - README.md
    - package.json
    - package-lock.json
    - tsconfig.json
    - tslint.json
    - angular.json
    - ionic.config.json
    - appspec.yml
    - scripts/*
    - src/**/*
    - www/**/*
    - node_modules/**/*
