version: 0.2

phases:
  install:
    commands:
      - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - echo Installing source NPM dependencies...
      - sudo apt-get update -y
      - sudo apt-get install -y apt-transport-https
      - sudo npm install forever -g
      - sudo npm install -g @angular/cli
      - sudo npm install
      - sudo node node_modules/node-sass/scripts/install.js
      - sudo npm rebuild node-sass
  build:
    commands:
      - echo Build started on `date`
      - sudo ng build --configuration=$BUILD_CONFIG
  post_build:
    commands:
      - aws s3 sync www/ s3://$S3_BUCKET/ --delete
      - aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths '/*'
      - sudo npm run generate-version
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - template.yml
    - README.md
    - package.json
    - package-lock.json
    - tsconfig.json
    - tslint.json
    - angular.json
    - ionic.config.json
    - appspec.yml
    - scripts/*
    - src/**/*
    - www/**/*
    - node_modules/**/*
