service: ${env:STACK_NAME}-appv3-redirect-${env:ENV}
functions:
useDotenv: true
provider: aws

resources:
  Resources:
    RedirectBucket:
      Type: "AWS::S3::Bucket"
      Properties:
        AccessControl: Private
        BucketName: ${env:STACK_NAME}-appv3-redirect-${env:ENV}
        LifecycleConfiguration:
          Rules:
            - AbortIncompleteMultipartUpload:
                DaysAfterInitiation: 7
              Status: Enabled
              Id: AbortIncompleteMultipartUpload
            - ExpirationInDays: 35
              Status: Enabled
              Id: DeletObjectsAfterExpirationInDays
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

    RedirectBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: RedirectBucket
        PolicyDocument:
          Statement:
            - Sid: S3-Bucket-Accesible via CDN OAI only
              Action: "s3:GetObject"
              Effect: Allow
              Resource: "arn:aws:s3:::${env:STACK_NAME}-appv3-redirect-${env:ENV}/*"
              Principal:
                CanonicalUser: !GetAtt RedirectCDNOriginAccessIdentity.S3CanonicalUserId
            - Sid: AllowSSLRequestsOnly
              Effect: Deny
              Principal: "*"
              Action: "s3:*"
              Resource:
                - !Sub "arn:aws:s3:::${env:STACK_NAME}-appv3-redirect-${env:ENV}"
                - !Sub "arn:aws:s3:::${env:STACK_NAME}-appv3-redirect-${env:ENV}/*"
              Condition:
                Bool:
                  "aws:SecureTransport": false

    RedirectCDNOriginAccessIdentity:
      Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: "Cloudfront Origin identity for ${env:STACK_NAME}-appv3-redirect-${env:ENV}"

    RedirectCDN:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Aliases:
            - ${env:APPV3_ALIAS}
          DefaultRootObject: index.html
          Comment: "Cloudfront Origin identity for ${env:STACK_NAME}-appv3-redirect-${env:ENV}"
          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
              - OPTIONS
            Compress: true
            DefaultTTL: 3600 # in seconds
            ForwardedValues:
              Cookies:
                Forward: none
              QueryString: false
            MaxTTL: 86400 # in seconds
            MinTTL: 60 # in seconds
            TargetOriginId: !Ref RedirectBucket
            ViewerProtocolPolicy: "redirect-to-https"
          Enabled: true
          HttpVersion: http2
          IPV6Enabled: true
          Origins:
            - DomainName: !GetAtt "RedirectBucket.RegionalDomainName"
              Id: !Ref RedirectBucket
              S3OriginConfig:
                OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${RedirectCDNOriginAccessIdentity}"
          PriceClass: "PriceClass_All"
          ViewerCertificate:
            AcmCertificateArn: "${env:CDNSharedACMCertificateArn}"
            MinimumProtocolVersion: "TLSv1.2_2021" # OLD VALUE:'TLSv1.2_2019'
            SslSupportMethod: "sni-only"
