################################################
#  GITHUB ACTION WORKFLOW NAME
################################################
name: Deploy to p2-stage environment


################################################
#  GITHUB ACTION EVENT TRIGGER
################################################
on:
  workflow_dispatch:
  push:
    branches: [ 'trunk-legacy' ]


################################################
#  GITHUB ACTION JOBS
################################################
jobs:
  deploy-p2-stage:
    name: deploy-p2-stage
    runs-on: ubuntu-latest
    environment: p2-stage
    permissions: write-all
    timeout-minutes: 15


################################################
#  GITHUB ACTIONS GLOBAL ENV VARIABLES  
################################################
    env:
      REGION : ap-southeast-2
      ENV : test # Valid values are dev,test,live only
      STACK_NAME: p2-stage # Valid values are au,us,uk,p2,lf,nu,p1-sandbox,p1-stage,p2-sandbox,shared only
      ROOTSTACK: app-v2
      CFNS3BucketName: devops-cfn-templates
      PRIVATES3BucketName: devops-shared-private
      PUBLICZONENAME: p2-stage.practera.com
      APPPUBLICZONENAME: p2-stage.practera.app
      BUILD_CONFIG: custom
      STATUSREPORTS3Bucket: deployment-status.practera.com
      STATUS: DEPLOYED
      REQUESTOR: ${{ github.event.inputs.REQUESTOR }}
      REASON: ${{ github.event.inputs.REASON }}
      ENDPOINT: app-old.p2-stage.practera.com
      BRANCH_TAG_NAME: trunk-legacy
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

################################################
#  GITHUB REPO CHECKOUT 
################################################
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          



################################################
#  NODE ENV
################################################    
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
      

################################################
#  NODE MODULES CACHE  
################################################
      - name: Cache node modules
        uses: actions/cache@v4
        id: cache-node-modules
        env:
          cache-name: cache
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.npm
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-


################################################
#  NODE MODULES INSTALL  
################################################
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run:  npm install
      
################################################
#  GET P2 STAGE AWS ORGANIZATION NUMBER
################################################
      - name: Get AWS Organization Number
        id: AWS_ORG
        run: |
          CENTRALIZED=$(echo $AWS_ACCOUNT_ID | jq -r .CENTRALIZED)
          P2STAGE=$(echo $AWS_ACCOUNT_ID | jq -r .P2STAGE)

          echo "::add-mask::$CENTRALIZED"
          echo "::add-mask::$P2STAGE"

          echo "CENTRALIZED=$CENTRALIZED" >> $GITHUB_OUTPUT
          echo "P2STAGE=$P2STAGE" >> $GITHUB_OUTPUT

################################################
#  AWS CLI CONFIGURATION - CENTRALIZED ACCOUNT
################################################
      - name: Configure AWS Credentials from CENTRALIZED Account
        uses: ./.github/actions/aws-oidc
        with:
          role-to-assume: arn:aws:iam::${{ steps.AWS_ORG.outputs.CENTRALIZED }}:role/github-restricted-role-to-assume
          region: ${{ env.REGION }}

###############################################################
#  SERVERLESS DEPLOYMENT VARIABLES FROM SHARED ACCOUNT
##############################################################
      - name: Serverless deployment variables created from shared account
        run: |
          cat >> .env <<EOF
          FILESTACKAWSID=$(aws secretsmanager get-secret-value --secret-id $STACK_NAME-DEPLOY-$ENV| jq --raw-output '.SecretString' | jq -r .FILESTACKID) 
          P1STACKAWSID=$(aws secretsmanager get-secret-value --secret-id $STACK_NAME-DEPLOY-$ENV| jq --raw-output '.SecretString' | jq -r .P1PRODID) 
         
          EOF
        env:  #TODO: Update once manually to new stack accordingly
          STACK_NAME: shared # Valid values are au,us,uk,p2,lf,nu,p1-sandbox,p1-stage,p2-sandbox,shared only
          ENV: live # Valid values are sandbox,stage,live only


################################################
#  AWS CLI CONFIGURATION - P2STAGE ACCOUNT
################################################
      - name: Configure AWS Credentials from P2STAGE Account
        uses: ./.github/actions/aws-oidc
        with:
          role-to-assume: arn:aws:iam::${{ steps.AWS_ORG.outputs.P2STAGE }}:role/github-restricted-role-to-assume
          region: ${{ env.REGION }}

###############################################################
#  ANGULAR ENVIRONMENT CREATION
##############################################################
      - name: Angular Environment creation
        run: |
          printf "Creating required secret variables for angular environment variable creation\n\n"

          export CUSTOM_APPKEY=$(aws secretsmanager get-secret-value --secret-id $STACK_NAME-AppKeySecret-$ENV| jq --raw-output '.SecretString' | jq -r .appkey) 
          export CUSTOM_FILESTACK_SIGNATURE=$(aws secretsmanager get-secret-value --secret-id $STACK_NAME-FilestackSecret-$ENV| jq --raw-output '.SecretString' | jq -r .signature) 
          export CUSTOM_FILESTACK_VIRUS_DETECTION=$(aws secretsmanager get-secret-value --secret-id $STACK_NAME-FilestackSecret-$ENV| jq --raw-output '.SecretString' | jq -r .virusdetection) 
          export CUSTOM_FILESTACK_KEY=$(aws secretsmanager get-secret-value --secret-id $STACK_NAME-FilestackSecret-$ENV| jq --raw-output '.SecretString' | jq -r .apikey)
          export CUSTOM_FILESTACK_POLICY=$(aws secretsmanager get-secret-value --secret-id $STACK_NAME-FilestackSecret-$ENV| jq --raw-output '.SecretString' | jq -r .policy)
          export CUSTOM_STACK_UUID=$(aws secretsmanager get-secret-value --secret-id $STACK_NAME-LoginCoreSecrets-$ENV| jq --raw-output '.SecretString' | jq -r .APP_STACK_UUID)
          export CUSTOM_PUSHER_APPID=$(aws secretsmanager get-secret-value --secret-id $STACK_NAME-PusherSecret-$ENV| jq --raw-output '.SecretString' | jq -r .app_id) 
          export CUSTOM_PUSHERKEY=$(aws secretsmanager get-secret-value --secret-id $STACK_NAME-PusherSecret-$ENV| jq --raw-output '.SecretString' | jq -r .key) 
          export CUSTOM_PUSHER_SECRET=$(aws secretsmanager get-secret-value --secret-id $STACK_NAME-PusherSecret-$ENV| jq --raw-output '.SecretString' | jq -r .secret) 
          export CUSTOM_PUSHER_CLUSTER=$(aws secretsmanager get-secret-value --secret-id $STACK_NAME-PusherSecret-$ENV| jq --raw-output '.SecretString' | jq -r .cluster) 
          export CUSTOM_INTERCOM=$(aws secretsmanager get-secret-value --secret-id $STACK_NAME-IntercomSecret-$ENV| jq --raw-output '.SecretString' | jq -r .app_id) 

          printf "Angular environment variable creation  complete\n\n"
          printf "Executing env.sh script\n\n"
          chmod +x env.sh && ./env.sh

          echo "Extracting chatbotSNStopicARN to send stack update"
          echo "ChatBotSNSTopicARN="$(aws cloudformation list-exports --query "Exports[?Name==\`$STACK_NAME-ChatBotSNSTopicARN-$ENV\`].Value" --no-paginate --output text) >> $GITHUB_ENV
          
        env:
          CUSTOM_PATH_IMAGE: /appv2/test/images/
          CUSTOM_PATH_VIDEO: /appv2/test/videos/
          CUSTOM_GRAPH_QL: https://core-graphql-api.${{ env.PUBLICZONENAME }}
          CUSTOM_API_ENDPOINT: https://admin.${{ env.PUBLICZONENAME }}/
          CUSTOM_S3_BUCKET: files.${{ env.PUBLICZONENAME }}
          CUSTOM_ENVIRONMENT: ${{ env.ENV }}
          CUSTOM_CHAT_GRAPH_QL: https://chat-api.${{ env.PUBLICZONENAME }}
          CUSTOM_GLOBAL_LOGIN_URL: https://app.login-stage.practera.com 
          CUSTOM_COUNTRY: AUS #TODO CHECK
          CUSTOMPLAIN_SKIPGLOBALLOGINFLAG: false
          CUSTOM_PATH_ANY: /appv2/test/any/
          CUSTOM_AWS_REGION: ${{ env.REGION }}
          CUSTOM_JS_ENVIRONEMENT: dev #TODO CHECK
          CUSTOM_LOGIN_API_URL: https://api.login-stage.practera.com
          CUSTOM_NEWRELIC: false
          CUSTOM_APPV3_URL: https://appv3.${{ env.PUBLICZONENAME }}
          CUSTOM_SWITCH_APP3: true


# ################################################
# #  PERFORM LINT TEST
# ################################################
      - name: Run lint test if present
        run:  |
          npm run lint --if-present

          
###############################################################
#  BUILD WEB PACKAGES
##############################################################
      - name: Build Web Packages
        run: |
          test -f src/environments/environment.ts && echo "environment here" || cp src/environments/environment.local.ts src/environments/environment.ts
          node_modules/.bin/ng build --configuration=${{ env.BUILD_CONFIG }}
          npm run generate-version


# # ###############################################################
# # #  PERFORM UNIT TEST
# # ##############################################################
#       - name: Performing Unit test
#         run: |
#           node_modules/.bin/ng test --karmaConfig=src/karma.conf.sonarci.js --no-watch


# # ###############################################################
# # #  SONARCLOUD SCANNER
# # ##############################################################
#       - name: Performing Sonarcloud Scanner
#         uses: SonarSource/sonarcloud-github-action@master
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


##########################################################
#  AWS S3 SYNC - SERVERLESS TEMPLATES 
##########################################################
      - name: AWS S3 Sync operation
        run: |
          
          aws s3 cp serverless.yml s3://$CFNS3BucketName/$STACK_NAME/$REGION/$ROOTSTACK/sls-templates/serverless.yml


##########################################################
#  CLOUDFORMATION EXPORT VARIABLES
##########################################################
      - name: Cloudformation Export variables
        run: |
          cat >> .env <<EOF
          CDNSharedACMCertificateArn=$(aws cloudformation list-exports --query "Exports[?Name==\`$STACK_NAME-CDNSharedACMCertificateArn-$ENV\`].Value" --no-paginate --output text)
          ChatBotSNSTopicARN=$(aws cloudformation list-exports --query "Exports[?Name==\`$STACK_NAME-ChatBotSNSTopicARN-$ENV\`].Value" --no-paginate --output text)
          
          
          EOF

###############################################################
#  SERVERLESS DEPLOYMENT
##############################################################
      - name: Serverless deployment
        run: |
          echo "Serverless Deploying Appv2"
          node_modules/.bin/serverless deploy
          rm serverless.yml .env
        env:
          APPV2S3BUCKET: app-old.${{ env.PUBLICZONENAME }}
          FILESS3BUCKET: files.${{ env.PUBLICZONENAME }}
          FILESS3BUCKETEXIST: true
          S3VERSIONING: true 
          NONCURRENTVERSION_EXPIREINDAYS: 30
          


##########################################################
#  AWS S3 SYNC OPERATIONS
##########################################################
      - name: AWS S3 Sync Operations
        run: |
          cp -R src/well-known www/.well-known/
          APP_V2_S3=$(aws cloudformation list-exports --query "Exports[?Name==\`$STACK_NAME-AppV2S3Bucket-$ENV\`].Value" --no-paginate --output text)
          aws s3 sync www/ s3://$APP_V2_S3 --delete


##########################################################
#  AWS CDN CACHE INVALIDATION
##########################################################
      - name: AWS Cloudfront Cache invalidation
        run: |
          APP_V2_CDN=$(aws cloudformation list-exports --query "Exports[?Name==\`$STACK_NAME-AppV2CloudFrontDistributionID-$ENV\`].Value" --no-paginate --output text)
          for i in $APP_V2_CDN;do aws cloudfront create-invalidation --distribution-id $i --paths "/*";done



# #########################################################
# # SLACK NOTIFICATION
# #########################################################  
      - name: Slack Notification
        if: always() # Pick up events even if the job fails or is canceled.
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }} # required
        with:
          status: ${{ job.status }}
          author_name: ${{ env.BRANCH_TAG_NAME }} - ${{ env.ROOTSTACK }} deployed to ${{ env.ENV }} environemnt in ${{ env.STACK_NAME }} AWS account
          mention: 'here'
          if_mention: failure,cancelled
          job_name: deploy-p2-stage # Match the name above.
          fields: repo,commit,eventName,ref,workflow,message,author,job,took
          custom_payload: |
            {
            username: 'GitHub Action CI WorkFlow',
            icon_emoji: ':github:',
            attachments: [{
              color: '${{ job.status }}' === 'success' ? 'good' : ${{ job.status }}' === 'failure' ? 'danger' : 'warning',
              text:
             `${process.env.AS_REPO}\n
              ${process.env.AS_COMMIT}\n
              ${process.env.AS_EVENT_NAME}\n
              @${process.env.AS_REF}\n
              @${process.env.AS_WORKFLOW}\n
              ${process.env.AS_MESSAGE}\n
              ${process.env.AS_AUTHOR}\n
              ${process.env.AS_JOB}\n
              ${process.env.AS_TOOK}`,
            }]
            }

          
# ################################################
# #  STATUS VARIABLE UPDATE
# ################################################ 
      - name: Deployment status variable update
        if: ${{ failure() }}
        run: |
          echo "STATUS=FAILURE" >> $GITHUB_ENV

# ################################################
# #  DEVOPS-DEPLOYMENT REPORT
# ################################################ 
      - name: DevOps Deployment Reporting
        if: always()
        run: |
          pip install --upgrade pip
          pip install --upgrade csvtotable
          export REASON=$(git log -2 --format=%s | sed -n 2p)
          export REQUESTOR=${{ github.actor }}

          aws s3 cp s3://$STATUSREPORTS3Bucket/deploy-reporting.sh deploy-reporting.sh
          chmod +x deploy-reporting.sh && ./deploy-reporting.sh
          echo "LINK="${GITHUB_REPOSITORY##*/}.html >> $GITHUB_ENV
          echo $REASON
          echo $REQUESTOR


